version: "3.8"

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      - /bin/bash
      - -c
      - poetry run uvicorn app.main:app --reload --host=0.0.0.0 --port=8000
    restart: always

  memind-postgres:
      image: postgres:15.4
      container_name: postgres
      environment:
        POSTGRES_USER: dev
        POSTGRES_PASSWORD: dev1234
        POSTGRES_DB: dev
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data


volumes:
  mysql_data:
    external: false
  redis_data:
    external: false
  pg_data:
    external: false
