version: "3.8"

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      - /bin/bash
      - -c
      #- alembic revision --autogenerate -m "Initialize" && poetry run uvicorn app.main:app --reload --host=0.0.0.0 --port=8000
      - alembic upgrade head && poetry run uvicorn app.main:app --reload --host=0.0.0.0 --port=8000
      - poetry run uvicorn app.main:app --reload --host=0.0.0.0 --port=8000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
    external: false
