"""update schema

Revision ID: 0c6bbda6cb0f
Revises: fad2f775af95
Create Date: 2024-03-16 14:31:42.089354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6bbda6cb0f'
down_revision: Union[str, None] = 'fad2f775af95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True))
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
