"""refreal code expire

Revision ID: 6e786b873cc3
Revises: 6ab43d5a0f04
Create Date: 2024-09-06 01:16:15.318278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e786b873cc3"
down_revision: Union[str, None] = "6ab43d5a0f04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "users",
        sa.Column(
            "referral_code_validity_period",
            sa.Integer,
            nullable=False,
            server_default="30",
        ),
    )

    op.add_column(
        "users", sa.Column("referral_code_creation_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "referral_code_validity_period",
            sa.Integer(),
            nullable=False,
            server_default="30",
        ),
    )

    # 기존 레코드에 기본값 설정
    op.execute(
        "UPDATE users SET referral_code_validity_period = 30 WHERE referral_code_validity_period IS NULL"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "referral_code_validity_period")
    op.drop_column("users", "referral_code_creation_date")
    # ### end Alembic commands ###
