"""image model to timestamp

Revision ID: 944fd4906178
Revises: b8c6258d43d7
Create Date: 2024-08-18 07:13:03.412262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = "944fd4906178"
down_revision: Union[str, None] = "b8c6258d43d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add the columns with a default value
    op.add_column(
        "images", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "images", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )

    # Step 2: Update existing rows with a default value
    op.execute("UPDATE images SET created_at = NOW(), updated_at = NOW()")

    # Step 3: Alter columns to set them as NOT NULL
    op.alter_column(
        "images", "created_at", existing_type=sa.DateTime(timezone=True), nullable=False
    )
    op.alter_column(
        "images", "updated_at", existing_type=sa.DateTime(timezone=True), nullable=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "updated_at")
    op.drop_column("images", "created_at")
    # ### end Alembic commands ###
