"""add chat message link

Revision ID: 6ab8e237be57
Revises: d3b37eefc4c3
Create Date: 2024-07-16 10:56:42.490373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ab8e237be57"
down_revision: Union[str, None] = "d3b37eefc4c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("date", sa.Date(), nullable=False))
    op.add_column("messages", sa.Column("conversation_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        None, "messages", "conversations", ["conversation_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("messages", "conversation_id")
    op.drop_column("conversations", "date")
    # ### end Alembic commands ###
