"""add reference code

Revision ID: 6ab43d5a0f04
Revises: 4e3abff4df90
Create Date: 2024-09-05 22:30:05.795600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ab43d5a0f04"
down_revision: Union[str, None] = "4e3abff4df90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("referrer_id", sa.Uuid(), nullable=True))
    op.add_column(
        "users", sa.Column("referral_code", sa.String(length=10), nullable=True)
    )
    op.create_index(
        op.f("ix_users_referral_code"), "users", ["referral_code"], unique=True
    )
    op.create_foreign_key(None, "users", "users", ["referrer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_referral_code"), table_name="users")
    op.drop_column("users", "referral_code")
    op.drop_column("users", "referrer_id")
    # ### end Alembic commands ###
