"""edit image,message,report,emotion model

Revision ID: b8c6258d43d7
Revises: bbef5b94ac95
Create Date: 2024-08-11 16:39:16.625615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b8c6258d43d7"
down_revision: Union[str, None] = "bbef5b94ac95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("emotion", sa.Column("total_score", sa.Integer(), nullable=False))
    op.add_column("emotion", sa.Column("joyful_score", sa.Integer(), nullable=False))
    op.drop_constraint("fk_emotion_report_id", "emotion", type_="foreignkey")
    op.drop_column("emotion", "fun_score")
    op.drop_column("emotion", "report_id")
    op.drop_constraint("images_message_id_fkey", "images", type_="foreignkey")
    op.drop_column("images", "message_id")
    op.add_column(
        "messages", sa.Column("image_url", sa.String(length=256), nullable=True)
    )
    op.alter_column(
        "report", "drawing_diary_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "report", "drawing_diary_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("messages", "image_url")
    op.add_column(
        "images", sa.Column("message_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "images_message_id_fkey", "images", "messages", ["message_id"], ["id"]
    )
    op.add_column(
        "emotion",
        sa.Column("report_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "emotion",
        sa.Column("fun_score", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_emotion_report_id", "emotion", "report", ["report_id"], ["id"]
    )
    op.drop_column("emotion", "joyful_score")
    op.drop_column("emotion", "total_score")
    # ### end Alembic commands ###
