"""add withdrawal model

Revision ID: bbef5b94ac95
Revises: 6ab8e237be57
Create Date: 2024-07-29 13:11:26.845853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbef5b94ac95"
down_revision: Union[str, None] = "6ab8e237be57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("delete_reason", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "delete_reason")
    # ### end Alembic commands ###
