"""add report model

Revision ID: bfacbf0a0598
Revises: ff2e3e7e8cec
Create Date: 2024-07-12 17:22:32.115239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bfacbf0a0598"
down_revision: Union[str, None] = "ff2e3e7e8cec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drawing_diary",
        sa.Column("drawing_image_id", sa.Uuid(), nullable=False),
        sa.Column("image_url", sa.String(length=256), nullable=False),
        sa.Column("image_title", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("drawing_image_id"),
    )
    op.create_index(
        op.f("ix_drawing_diary_drawing_image_id"),
        "drawing_diary",
        ["drawing_image_id"],
        unique=False,
    )
    op.create_table(
        "report_summary",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contents", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_report_summary_id"), "report_summary", ["id"], unique=False
    )
    op.create_table(
        "report",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("drawing_diary_id", sa.Uuid(), nullable=False),
        sa.Column("emotion_id", sa.Uuid(), nullable=False),
        sa.Column("report_summary_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["drawing_diary_id"],
            ["drawing_diary.drawing_image_id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_summary_id"],
            ["report_summary.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_report_id"), "report", ["id"], unique=False)
    op.create_table(
        "emotion",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("comfortable_score", sa.Integer(), nullable=False),
        sa.Column("happy_score", sa.Integer(), nullable=False),
        sa.Column("sad_score", sa.Integer(), nullable=False),
        sa.Column("fun_score", sa.Integer(), nullable=False),
        sa.Column("annoyed_score", sa.Integer(), nullable=False),
        sa.Column("lethargic_score", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_emotion_id"), "emotion", ["id"], unique=False)
    op.create_table(
        "tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("report_summary_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_summary_id"],
            ["report_summary.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_id"), "tags", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tags_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_emotion_id"), table_name="emotion")
    op.drop_table("emotion")
    op.drop_index(op.f("ix_report_id"), table_name="report")
    op.drop_table("report")
    op.drop_index(op.f("ix_report_summary_id"), table_name="report_summary")
    op.drop_table("report_summary")
    op.drop_index(op.f("ix_drawing_diary_drawing_image_id"), table_name="drawing_diary")
    op.drop_table("drawing_diary")
    # ### end Alembic commands ###
