"""edit image link

Revision ID: e64f50e2c2ce
Revises: b8c6258d43d7
Create Date: 2024-08-18 11:39:48.344314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e64f50e2c2ce"
down_revision: Union[str, None] = "b8c6258d43d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("message_id", sa.Uuid(), nullable=True))
    op.add_column(
        "images", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "images", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.create_foreign_key(None, "images", "messages", ["message_id"], ["id"])
    op.drop_column("messages", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "image_url", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "images", type_="foreignkey")
    op.drop_column("images", "updated_at")
    op.drop_column("images", "created_at")
    op.drop_column("images", "message_id")
    # ### end Alembic commands ###
