"""edit image model

Revision ID: 12cd6f8b389d
Revises: bfacbf0a0598
Create Date: 2024-07-12 17:48:21.769295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12cd6f8b389d"
down_revision: Union[str, None] = "bfacbf0a0598"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("conversation_id", sa.Uuid(), nullable=True))
    op.add_column("images", sa.Column("message_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "images", "messages", ["message_id"], ["id"])
    op.create_foreign_key(None, "images", "conversations", ["conversation_id"], ["id"])
    op.create_foreign_key(None, "report", "emotion", ["emotion_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "report", type_="foreignkey")
    op.drop_constraint(None, "images", type_="foreignkey")
    op.drop_constraint(None, "images", type_="foreignkey")
    op.drop_column("images", "message_id")
    op.drop_column("images", "conversation_id")
    # ### end Alembic commands ###
