"""user delete reasons

Revision ID: 8901d415592d
Revises: ec38821f02e1
Create Date: 2024-08-24 10:01:05.520149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8901d415592d"
down_revision: Union[str, None] = "ec38821f02e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "delete_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("users", "delete_reason")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "delete_reason", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "delete_reasons")
    # ### end Alembic commands ###
