"""refreal code expire created

Revision ID: 95b3d9b1ca6c
Revises: 6e786b873cc3
Create Date: 2024-09-06 01:34:25.454998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95b3d9b1ca6c"
down_revision: Union[str, None] = "6e786b873cc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("referral_code_creation_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "referral_code_creation_date")
    # ### end Alembic commands ###
