"""edit emotion,reportn

Revision ID: 73227de86114
Revises: bbef5b94ac95
Create Date: 2024-08-11 09:48:19.845634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73227de86114"
down_revision: Union[str, None] = "bbef5b94ac95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("emotion", sa.Column("joyful_score", sa.Integer(), nullable=False))
    op.drop_constraint("fk_emotion_report_id", "emotion", type_="foreignkey")
    op.drop_column("emotion", "report_id")
    op.drop_column("emotion", "fun_score")
    op.alter_column(
        "report", "drawing_diary_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "report", "drawing_diary_id", existing_type=sa.UUID(), nullable=False
    )
    op.add_column(
        "emotion",
        sa.Column("fun_score", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "emotion",
        sa.Column("report_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_emotion_report_id", "emotion", "report", ["report_id"], ["id"]
    )
    op.drop_column("emotion", "joyful_score")
    # ### end Alembic commands ###
