"""edit image,message model

Revision ID: 79b9d842fbde
Revises: 73227de86114
Create Date: 2024-08-11 15:23:23.423991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79b9d842fbde"
down_revision: Union[str, None] = "73227de86114"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("images_message_id_fkey", "images", type_="foreignkey")
    op.drop_column("images", "message_id")
    op.add_column(
        "messages", sa.Column("image_url", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "image_url")
    op.add_column(
        "images", sa.Column("message_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "images_message_id_fkey", "images", "messages", ["message_id"], ["id"]
    )
    # ### end Alembic commands ###
