"""add snowflake report

Revision ID: 4e3abff4df90
Revises: d0d9ed663f47
Create Date: 2024-08-24 12:15:52.873774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e3abff4df90"
down_revision: Union[str, None] = "d0d9ed663f47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("report", sa.Column("snowflake_id", sa.BigInteger(), nullable=False))
    op.create_index(
        op.f("ix_report_snowflake_id"), "report", ["snowflake_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_snowflake_id"), table_name="report")
    op.drop_column("report", "snowflake_id")
    # ### end Alembic commands ###
